version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: web
    container_name: laravel_app
    env_file:
      - .env
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - redis
      - nginx
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "8080:80" # Changed to avoid conflict with the app service
    volumes:
      - .:/var/www/html
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
